name: Run Cron

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 8,14,20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v3

      # Update LAST_UPDATE text file to latest date
      - name: Update LAST_UPDATE file
        run: echo $(date +"%Y-%m-%d") > LAST_UPDATE.txt

      # Generate all statistics images
      - name: Run Cron
        run: |
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
          EXCLUDE_FORKED_REPOS: true

      # Commit all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "retsu14/cron_job"
          git config --global user.email "tajanlangitelieser19@gmail.com"
          git add .
          # Force the build to succeed, even if no files were changed
          git commit -m 'Update generated files' || true
          git push
